name: build-and-deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
      -
        name: Github Checkout
        uses: actions/checkout@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: dockerfile
          tags: ${{ github.repository }}:${{ github.ref_name }}_0.0.2
          github-token: ${{ github.token }}
