name: build-and-deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
      -
        name: Github Checkout
        uses: actions/checkout@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v1

      - name: "Append ARM buildx builder"
        uses: baschny/append-buildx-action@v1
        with:
          builder: ${{ steps.builder.outputs.name }}
          endpoint: "tcp://the-fqdn-or-ip-of-arm64-host:2375"

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: dockerfile
          tags: ${{ github.repository }}:${{ github.ref_name }}
          github-token: ${{ github.token }}
          platforms: linux/arm64
